### ISSUE TITLE
stable API?

### ISSUE THREAD

**Issue by umlaeute** [rbdannenberg/o2#17]
how stable is the o2 API?

i noticed that o2 tends towards a version 2.0, changing the name of some types, the call semantics of a few functions and removing some functions alltogether.

given that version 2 is indeed a major version bump, this is totally ok and suggests that the API *can* indeed be considered stable according to [semantic versioning](https://semver.org).

do i get this correct?
a stable API means that it should be possible to make use of *dynamic libraries* (see #16 ), as opposed to building everything as static.
i'm mostly interested, because i'd like to get `o2` into the Debian/Ubuntu/... universe as a proper package.

sidenote: for static building this is not an issue, but the public API (`o2.h`) contains conditional symbols, e.g.  https://github.com/rbdannenberg/o2/blob/cfda3abf5471491a1b12e15f8473cc65069bcede/src/o2.h#L1668-L1685

is there any reason to not make the symbols in the header-files unconditional, and just provide dummy implementations if the library is compiled without debugging/hub/osc/bundles/... support?

**Comment by rbdannenberg** [comment]
Did you get my email reply? I'm curious.

**Comment by rbdannenberg** [comment]
I'm not sure what's happened with this. Yes, I consider the O2 API to be stable -- at least if anything incompatible is introduced, it will become another version. There's a fair amount of conditional compilation so that unwanted features can be turned off for embedded systems (or anyone else). It turns out these do not make a really big difference, so it makes sense to compile with the defaults. Defaults are intentionally set up so that no definition gives you the default which usually means FEATURE ENABLED, e.g. do NOT define O2_NO_OSC and you get support for Open Sound Control. I hate the double negatives, but it seems better than requiring Makefiles to explicitly ENABLE all the features.

By NOT defining O2_NO_DEBUG, you get the full API including the debug support -- that's going to assume printf, but that's OK on Linux, and it will add more code, but not that much, so it seems like the right default. You can still compile with optimization on while leaving O2_NO_DEBUG undefined (DEBUG *enabled*). Calls will then be added to translate error codes to strings, and there's support to print a lot of trace info to stdout when certain flags are set at runtime.

**Comment by umlaeute** [comment]
thanks for the clarification. i think I'm settled.
