### ISSUE TITLE
`o2_malloc` returns unaligned memory

### ISSUE THREAD

**Issue by vnorilo** [rbdannenberg/o2#19]
![Screenshot 2021-12-08 at 0 20 18](https://user-images.githubusercontent.com/14020514/145115098-a5a4e4dd-cb1a-4694-9c15-50521bedab4c.png)

`o2_malloc` seems to return unaligned memory in my build. As a result, `osc_to_o2` and I suspect much of o2 message parsing is broken.

**Comment by rbdannenberg** [comment]
I don't see how this could happen. Are you doing anything non-default like passing in an initial block of memory or using your own malloc (O2 falls back to malloc() if it runs out of its own pre-allocated chunk of memory).

Alternatively, could you check if the parameter "elem" is 8-byte aligned when O2queue::push() is called in o2atomic.cpp? I added checks for that and for "result" alignment in o2_malloc line 466, and everything is aligned. 

I assume you are on a 64-bit architecture?

**Comment by vnorilo** [comment]
This run was wihtout any call to `o2_memory`. I do not install any custom malloc handlers. This is macOS 11.5.1 on 64-bit Intel and Xcode 13.1 (13A1030d). O2 calls happen in their own `std::thread`, which starts with the following initialization:

```
o2_initialize(CL::o2_app().c_str());
o2_clock_set(NULL, NULL);
o2_service_new(serviceName.c_str());
o2_osc_port_new(serviceName.c_str(), CL::osc_port(), 0);
```

and then proceeds to run `o2_poll()` and a task queue that calls `o2_method_new`. 

I added the breakpoint you suggested, and the first occurrence received a 16-byte aligned `elem`. The second one was only 4-aligned though.

![image](https://user-images.githubusercontent.com/14020514/145351021-a0429cff-cb2b-48c6-b1f5-30f1f330ed97.png)

As you can see, it is the storage pointer in a `Vec<char>`. It is coming from the `O2_MALLOCNT` in `Vec<char>::init(int siz, bool z)`.

It is caused by an odd `realsize` bumping the `chunk` pointer by 17 bytes when heapifying some string in `o2_init`. So the malfunctioning bit is the odd `realsize`. 

![image](https://user-images.githubusercontent.com/14020514/145353985-4abf3362-1cb3-410f-b2bd-9285ca7fea85.png)

I believe this is caused by `postlude_struct` being 1 bytes long when empty; C++ mandates that any struct instance has a unique pointer, which is why compilers will add this ghost byte to empty structs.

**Comment by vnorilo** [comment]
https://github.com/rbdannenberg/o2/pull/20

**Comment by rbdannenberg** [comment]
Thanks for figuring this out! In your changes I see some conditionals added to CMake files to remove optional files like sharedmem.cpp when disabled. My solution to that was to put the entire body of sharedmem.cpp inside #ifdef O2_NO_SHAREDMEM, so if you disable the shared memory support/feature, no code is actually generated. This seems simpler and more robust than coordinating variables in CMake (BUILD_WITH_SHAREDMEM_SUPPORT) with defines in C++ (O2_NO_SHAREDMEM). Is there any need to have this addition to CMake code?

**Comment by vnorilo** [comment]
You are correct; I made some changes due to being unable to build O2, but the changes to remove translation units from projects are probably unnecessary and in any case not related to the pull request. I adjusted it to contain just the change discussed in this issue, plus a straightforward fix to the link dependencies of the o2 shared library. Thanks!

**Comment by vnorilo** [comment]
Thank you for merging!

**Comment by rbdannenberg** [comment]
FYI. I tried to run some performance tests with optimization turned on, and O2 crashed with what looks like non-16-byte-aligned atomic structures.  But there's extra space in data structures and code to calculate the actual location of atomic list headers to make sure they are properly aligned. I couldn't single step the code because the problem only happened with optimization on, but when I passed in malloc and free to replace the default O2 real-time memory allocation, things worked. So I modified O2's memory allocator to be 16-byte aligned (which is tricky because preceding every object is an 8-byte length, so every object actually has an odd number of 8-byte units preceded by the 8-byte length (and there's more messiness with O2MEM_DEBUG, which inserts a preamble and postlude to every object to aid in debugging -- but that has been invaluable in tracking down memory leaks). I just pushed the changes.

**Comment by rbdannenberg** [comment]
FYI I found in my efforts to add features to o2mem.cpp for debugging, I introduced some bugs. I also discovered Windows atomic support in C/C++ looks like they may not be using lock-free primitives. I did a lot of work on o2mem.cpp -- mostly making it slightly simpler, solved some memory leaks in O2, and switched Windows implementation to use Windows SList primitives that are claimed to be lock-free. Also O2MEM_DEBUG adds some locks if it is non-zero (zero is default for Release builds). So the current head O2 version on master is now improved. Thanks for sending me down this path.

**Comment by vnorilo** [comment]
Thank you for all the work! I'm tracking your changes as I'm working on integrating O2 2.0 to the Kronos runtime.

**Comment by rbdannenberg** [comment]
For what it's worth, I've started a project to build an audio server that gets populated with unit generators from Faust, and which uses O2 for control. In anticipation of computing audio on high-priority threads that should not make system calls (which excludes using sockets), there's a shared memory interface that allows a full O2 process to run in one thread and forward messages to/from an audio thread sharing memory. It's a little trickier than I first thought because when you are not receiving audio callbacks, you might need another thread to handle messages, but that's not trivial given the use of thread-local variables and the need for mutual exclusion. Feel free to discuss any issues that come up at your end either here or directly via email.
